// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACbepov3Jv2QRPlQglYVCtNDTKZXFGL2c',
    appId: '1:15000995615:web:95abaabc4e2e5b58e8522a',
    messagingSenderId: '15000995615',
    projectId: 'letsmerge-be',
    authDomain: 'letsmerge-be.firebaseapp.com',
    storageBucket: 'letsmerge-be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRMx7J24vzqbuC0lGn-l2d3R9xruP-D8s',
    appId: '1:15000995615:android:d6ef85b2ff237a9de8522a',
    messagingSenderId: '15000995615',
    projectId: 'letsmerge-be',
    storageBucket: 'letsmerge-be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOFYkZjrBrqSE--RwNiKNCTdofUs3acpk',
    appId: '1:15000995615:ios:efb0fcb681141a2fe8522a',
    messagingSenderId: '15000995615',
    projectId: 'letsmerge-be',
    storageBucket: 'letsmerge-be.firebasestorage.app',
    iosBundleId: 'com.letsmerge.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOFYkZjrBrqSE--RwNiKNCTdofUs3acpk',
    appId: '1:15000995615:ios:efb0fcb681141a2fe8522a',
    messagingSenderId: '15000995615',
    projectId: 'letsmerge-be',
    storageBucket: 'letsmerge-be.firebasestorage.app',
    iosBundleId: 'com.letsmerge.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACbepov3Jv2QRPlQglYVCtNDTKZXFGL2c',
    appId: '1:15000995615:web:fc319c9d5c9aa414e8522a',
    messagingSenderId: '15000995615',
    projectId: 'letsmerge-be',
    authDomain: 'letsmerge-be.firebaseapp.com',
    storageBucket: 'letsmerge-be.firebasestorage.app',
  );
}
